### ISSUE TITLE
希望能独立引入，所以来到这个项目，然而……

### ISSUE THREAD

**Issue by exoticknight** [ElemeFE/vue-picker#1]
首先，从 npm 安装完之后，引入竟然是用 ‘vue-picker’，被文档坑了
然后，在终于解决引入问题之后，又报错 ‘build.js:9221 [Vue warn]: Attributes ":slots", "rotate-effect", ":visible-item-count" are ignored on component <picker> because the component is a fragment instance’，excuse me？文档是这么用的啊……
最后，这套组件估计是没法用的……大家小心了
PS：不知道为什么官网看起来就很好看，被骗了不开心……
PPS：也有可能只是因为我水平差，求拍

**Comment by exoticknight** [comment]
我换了台机器测试，似乎又可以用 'mint-picker' 引入了，是因为 npm 版本不一样吗？
你可以看到 npm 上的是 https://www.npmjs.com/package/vue-picker，然后会重定向到这个项目
反正我是彻底晕了
这个组件其实写得很好啊（从 demo 上来看），所以用不了实在让我抓狂，尤其 deadline 临近……

**Comment by airyland** [comment]
给个建议，大部分问题文档都可以解决。`警告`和`错误`是两回事,只要是`片断`组件都会有这个警告。开源耗费时间又不能赚钱为什么特意来骗你？卖萌可耻，不要把issue当论坛。

**Comment by exoticknight** [comment]
@airyland 
我其实是个挺冷酷的人，只不过是认为用了 github 上别人的代码，就不太好对作者太严厉。既然你们觉得口气比较软可耻，那我直说好了。
我也是编程好几年的人了，你说文档能解决我难道不清楚？文档能解决我还会花时间麻烦作者？一开始我就说了文档有问题。
开源不骗人，只是容易坑人，因为不赚钱，只能靠个人直制力推动。

**Comment by pb-cheung** [comment]
文档是该更新下
